name = "rj-portfolio-site"
main = "out/_worker.js" # OpenNext generates a Worker entry here
compatibility_date = "2025-09-22" # today’s date
type = "javascript"

[site]
bucket = "./out"
entry-point = "workers-site"